Blogs/Blogs/Models/Setting.cs
namespace Blogs.Models
{
    public class Setting
    {
        public int Id { get; set; }
        public string? SiteName { get; set; }
        public string? Title { get; set; }
        public string? ShortDescription { get; set; }
        public string? ThumbnailUrl {  get; set; }
        public string? FacebookUrl {  get; set; }
        public string? TwitterUrl { get; set; }
        public string? GithubUrl { get; set; }
    }
}

Blogs/Blogs/Areas/Admin/Controllers/SettingController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Blogs.Data;
using Blogs.Models;
using Blogs.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blogs.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SettingController : Controller
    {
        private readonly ApplicationDbContext _context;
        public INotyfService _notification { get; }
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SettingController(ApplicationDbContext context, INotyfService notification, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _notification = notification;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var settings = _context.Settings!.ToList();
            if(settings.Count > 0)
            {
                var vm = new SettingVM()
                {
                    Id = settings[0].Id,
                    SiteName = settings[0].SiteName,
                    Title = settings[0].Title,
                    ShortDescription = settings[0].ShortDescription,
                    ThumbnailUrl = settings[0].ThumbnailUrl,
                    FacebookUrl = settings[0].FacebookUrl,
                    GithubUrl = settings[0].GithubUrl,
                    TwitterUrl = settings[0].TwitterUrl,
                };
                return View(vm);
            }
            var setting = new Setting()
            {
                SiteName = "Demo Name"
            };
            await _context.Settings!.AddAsync(setting);
            await _context.SaveChangesAsync();
            var createdSettings = _context.Settings!.ToList();
            var createdVm = new SettingVM()
            {
                Id = createdSettings[0].Id,
                SiteName = createdSettings[0].SiteName,
                Title = createdSettings[0].Title,
                ShortDescription = createdSettings[0].ShortDescription,
                ThumbnailUrl = createdSettings[0].ThumbnailUrl,
                FacebookUrl = createdSettings[0].FacebookUrl,
                GithubUrl = createdSettings[0].GithubUrl,
                TwitterUrl = createdSettings[0].TwitterUrl,
            };
            return View(createdVm);
        }

        [HttpPost]
        public async Task<IActionResult> Index(SettingVM vm)
        {
            if (!ModelState.IsValid) { return View(vm); }
            var setting = await _context.Settings!.FirstOrDefaultAsync
                (x => x.Id == vm.Id);
            if (setting == null) 
            {
                _notification.Error("Something Went Wrong");
                 return View(vm); 
            }
            setting.SiteName = vm.SiteName; 
            setting.Title = vm.Title;
            setting.ShortDescription = vm.ShortDescription; 
            setting.FacebookUrl = vm.FacebookUrl;
            setting.GithubUrl = vm.GithubUrl;
            setting.TwitterUrl = vm.TwitterUrl;
            setting.ThumbnailUrl = vm.ThumbnailUrl; 
            
            if(vm.Thumbnail != null)
            {
                setting.ThumbnailUrl = UploadImage(vm.Thumbnail);
            }
            await _context.SaveChangesAsync();
            _notification.Success("Setting Updated Successfully");
            return RedirectToAction("Index", "Post", new { area = "Admin" });
        }
        private string UploadImage(IFormFile file)
        {
            string uniqueFileName = "";
            var folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "thumbnails");
            uniqueFileName = Guid.NewGuid().ToString() + " " + file.FileName;
            var filePath = Path.Combine(folderPath, uniqueFileName);
            using (FileStream filestream = System.IO.File.Create(filePath))
            {
                file.CopyTo(filestream);
            }
            return uniqueFileName;
        }
    }
}

Blogs/Blogs/Areas/Admin/Views/Setting/Index.cshtml
@model Blogs.ViewModels.SettingVM
@{

    ViewData["Title"] = "Site Setting";

}
<div class="container-fluid">
    <a class="btn btn-primary mb-1" asp-action="Index" asp-controller="User">Go Back</a>
    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title text-white">Setting</h4>
        </div>
        <div class="card-body">
            <form asp-action="Index" asp-controller="Setting" asp-area="Admin" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <div class="row mb-2">
                    <div class="col-9">
                        <div class="mb-2">
                            <label>Site Name</label>
                            <input type="text" asp-for="SiteName" class="form-control" />
                            <span asp-validation-for="SiteName" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Title</label>
                            <input type="text" asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                       
                        <div class="mb-2">
                            <label>Short Description</label>
                            <input type="text" asp-for="ShortDescription" class="form-control" />
                            <span asp-validation-for="ShortDescription" class="text-danger"></span>
                        </div>
                        
                        <div class="mb-2">
                            <label>Facebook Url</label>
                            <input type="text" asp-for="FacebookUrl" class="form-control" />
                            <span asp-validation-for="FacebookUrl" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Github Url </label>
                            <input type="text" asp-for="GithubUrl" class="form-control" />
                            <span asp-validation-for="GithubUrl" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Twitter Url</label>
                            <input type="text" asp-for="TwitterUrl" class="form-control" />
                            <span asp-validation-for="TwitterUrl" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="mb-2">
                            @{
                                if (Model.ThumbnailUrl == null)
                                {
                                    <img src="~/thumbnails/default_image.png" class="img-fluid" id="thumbnail" />

                                }
                                else
                                {
                                    <img src="~/thumbnails/@Model.ThumbnailUrl" class="img-fluid" id="thumbnail" />

                                }

                            }
                        </div>
                        <div class="mb-2">

                            <label>Thumbnail</label>
                            <input type="file" asp-for="Thumbnail" class="custom-file" />
                            <span asp-validation-for="Thumbnail" class="text-danger"></span>

                        </div>
                    </div>
                </div>

                <div class="mb-2">
                    <button type="submit" class="btn btn-primary w=100">Save</button>
                </div>
            </form>
        </div>
    </div>

</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(".custom-file").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            document.getElementById('thumbnail').src = window.URL.createObjectURL(this.files[0])
        });
    </script>
}